Update task.ts camelCase 84 1
MrRefactoring/confluence.js pull request #86
Opened 2023-06-24 07:03 UTC by frodri13

2023-06-26 20:21 UTC, MrRefactoring requested changes

2023-06-26 20:21 UTC, MrRefactoring commented on src/version2/task.ts
> +        'body-format': parameters.bodyFormat,
I getting an error when try to build the lib. Could you please check how 
[Augustus Thomas](https://github.com/augustus-thomas) did [similar changes](https://github.com/MrRefactoring/confluence.js/pull/85) and fix it?

![The error](https://github.com/MrRefactoring/confluence.js/assets/10329528/3cae8f4d-5636-4cac-9ed8-09a75444abcc)

2023-06-27 13:40 UTC, frodri13 commented
Hello @MrRefactoring thank you for the tip. I closed the other one and put the changes into this PR. Let me know if ok and I will proceed to do the same for other issues.

2023-06-27 14:04 UTC, MrRefactoring approved these changes

2023-06-27 14:05 UTC, merged

2023-06-27 14:05 UTC, MrRefactoring commented
Thank you very much!